# Generated by Django 3.2.8 on 2021-10-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.CharField(max_length=200)),
                ('RegionDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolID', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectProvided', models.CharField(max_length=200)),
                ('numberofTeachers', models.IntegerField(null=True)),
                ('attendanceRate', models.IntegerField(null=True)),
                ('dropoutRate', models.IntegerField(null=True)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.region')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseholdID', models.IntegerField(null=True)),
                ('averageeducationlevel', models.CharField(max_length=200)),
                ('HouseholdIncome', models.IntegerField(null=True)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.region')),
            ],
        ),
    ]
