# Generated by Django 3.2.8 on 2021-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='id',
        ),
        migrations.AlterField(
            model_name='household',
            name='HouseholdID',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
