# Generated by Django 3.2.8 on 2021-10-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20211008_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationlevel',
            old_name='type',
            new_name='type_of_education',
        ),
        migrations.AlterField(
            model_name='household',
            name='averageeducationlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educationlevel'),
        ),
    ]
