# Generated by Django 3.2.8 on 2021-10-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_household_averageeducationlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
